Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: storeId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: storeId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: postIdIndex
          KeySchema:
            - AttributeName: storeId
              KeyType: HASH
          Projection:
            ProjectionType: "ALL"